Remove lchown method from the list of method.
Because of that:
/app/node_modules/co-fs/index.js:64
                       ^
Error: fs.lchown does not exist
    at /app/node_modules/co-fs/index.js:64:24
    at Array.forEach (native)
    at Object.<anonymous> (/app/node_modules/co-fs/index.js:63:9)
    at Module._compile (module.js:450:26)
    at Object.Module._extensions..js (module.js:468:10)
    at Module.load (module.js:350:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:358:17)
    at require (module.js:374:17)